### ISSUE TITLE
sample code is not working

### ISSUE THREAD

**Issue by workplaylifecycle** [habuma/spring-in-action-4-samples#17]
[sample code](https://github.com/habuma/spring-in-action-4-samples/tree/master/Chapter_02/stereo-autoconfig) here those sample code can not run test, something like [issue asked on stackoverflow](https://stackoverflow.com/questions/38790336/spring-in-action-chapter-2-example-dont-work), is there anyone knows the issue? thanks

**Comment by workplaylifecycle** [comment]
ok, forget about it, I think it's package version conflict issue, I just cloned the total github project, then better, but for this test (link: https://raw.githubusercontent.com/habuma/spring-in-action-4-samples/master/Chapter_02/stereo-autoconfig/src/test/java/soundsystem/CDPlayerTest.java) raw.githubusercontent.com/habuma/spring-…, mac os x passed while windows failed, both IntelliJ IDEA

**Comment by workplaylifecycle** [comment]
org.junit.ComparisonFailure: expected:<... Band by The Beatles[]
> but was:<... Band by The Beatles[
]
>
    at org.junit.Assert.assertEquals(Assert.java:115)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at soundsystem.CDPlayerTest.play(CDPlayerTest.java:34)

org.junit.contrib.java.lang.system.StandardOutputStreamLog#getLog(), this guy, I think it has different behavior between Max OS X and Windows
